//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsNew
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CourseId { get; set; }
        public string MoedA { get; set; }
        public string MoedB { get; set; }
        public string FinalGrade { get; set; }
    }
}
